---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2022/11/16 16:43
---


-- 以只读方式打开文件
file = io.open("test.lua", "r")

file:seek("end",-25)
print(file:read("*a"))

-- 关闭打开的文件
file:close()