---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2022/11/16 15:34
---

--mytable = setmetatable({ key1 = "value1" }, {
--    __index = function(mytable, key)
--        if key == "key2" then
--            return "metatablevalue"
--        else
--            return nil
--        end
--    end
--})
--
--print(mytable.key1, mytable.key2)
--
--mytable = setmetatable({key1 = "value1"}, { __index = { key2 = "metatablevalue" } })
--print(mytable.key1,mytable.key2)
--
--
--print("==========csdcsdcsdcsdcsd=========")
--mymetable = setmetatable({key1 = "value1"}, {__newindex = mymetable})
--
--print(mytable.key1)
--
--mytable.newkey = "新值2"
--print(mytable.newkey, mytable.key1)
--
--mytable.key1 = "新值1"
--print(mytable.key1, mymetable.key1)


print("=======")

function table_maxn(t)
    local mn = 0
    for k, v in pairs(t) do
        if mn < k then
            mn = k
        end
    end
    return mn
end


mytable = setmetatable({1,2,3}, {
    __add = function(mytable, newtable)
        for i = 1, table_maxn(newtable) do
            table.insert(mytable, table_maxn(mytable) + 1, newtable[i])
        end
        return mytable
    end
})

for k, v in ipairs(mytable) do
    print(k, v)
end

print("--------")
secondtable = {4,5,6}

mytable = mytable + secondtable
for k, v in ipairs(mytable) do
    print(k, v)
end
